language: perl
bundler_args: --deployment
cache: bundler

perl:
  - "5.24"
  - "5.22"
  - "5.20"
  - "5.18"
  - "5.16"
  - "5.14"
  - "5.12"
  - "5.10"
 
install:
   - cpanm --quiet --notest --skip-satisfied Dist::Zilla
   - cpanm Test::NoTabs
   - "apt-get install libgd"
   - "dzil authordeps | grep -vP '[^\\w:]' | cpanm --verbose --notest --skip-satisfied"
   - "dzil listdeps   | grep -vP '[^\\w:]' | cpanm --verbose --skip-satisfied"

script:
  - dzil authordeps --missing | cpanm --verbose --notest --skip-satisfied
  - dzil smoke --release --author

notifications:
  email:
    recipients:
      - worthmine@gmail.com
    on_success: change
    on_failure: never
